version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atom_chat_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/db.sqlite3
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
