"""create users table

Revision ID: e032ad618996
Revises: 058c5ee7d7ae
Create Date: 2024-10-28 16:12:33.664056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e032ad618996'
down_revision: Union[str, None] = '058c5ee7d7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_user', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    op.drop_column('users', 'is_user')
    # ### end Alembic commands ###
